### ISSUE TITLE
my dashboard

### ISSUE THREAD

**Issue by Laoujin** [TTC-AAlst/TTC-React-Front#3]
- [ ]  laatste 2 (?) match en volgende 2 (?) matchen van jouw ploeg Sporta/VTTL
- [ ]  positie jouw team(s) in de ranking
- [ ] data over hoe jij het deed dit seizoen (matchen gewonnen/verloren, ...)
- [ ]  voorbije matchen met recente activiteit (comments) extra in de verf zetten

**Comment by Laoujin** [comment]
Excellent time to also introduce the new logo on the main page

And perhaps also to redo the footer (not so good on mobile currently)
